name = 'Rusty Typewriter Better'
license = 'MIT'
licenselink = 'https://github.com/lucwl/rusty-typewriter-better/LICENSE'
description = 'A rusty hugo theme'

homepage = 'https://github.com/lucwl/rusty-typewriter-better'
demosite = 'https://math-queiroz.github.io/rusty-typewriter'

tags = ["responsive", "minimal", "blog"]
features = ["blog", "themes", "search"]

[author]
  name = 'Matheus Queiroz'
  homepage = 'https://github.com/math-queiroz'
